### ISSUE TITLE
Wrong command in readme

### ISSUE THREAD

**Issue by RobertZickler** [issaiass/realsense2_description#2]
Hey everyone,
first of all: thanks for the package. Nice work.
But going through the readme I think there is a mistake
Following
_Finally launch the application by:
    `roslaunch realsense2_description view_d435_model.launch`_
results in a launch of RViz but no Gazebo. And not
_When everything ends, you must see gazebo and rviz loaded and the intel realsense d435 camera with an empty world._

So I think it should be 
`roslaunch realsense2_description view_d435_model_rviz_gazebo.launch`
which results in the desired behavior.

Cheers
Robert

**Comment by issaiass** [comment]
OK, i will do the changes... thanks
